CREATE TABLE [dbo].[SocksPair](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Colour] [nvarchar](50) NULL,
 CONSTRAINT [PK_SocksPair] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO